### ISSUE TITLE
Update start page

### ISSUE THREAD

**Issue by kevinhinterlong** [jtmcn/archwiki-viewer#11]
update the html to the current wiki [main page](https://wiki.archlinux.org/index.php/Main_page)

**Comment by jtmcn** [comment]
This is the most important issue to be fixed before an update is published.

**Comment by kevinhinterlong** [comment]
I've got in in a local branch right now if you want me to send a PR. 

We should also check out the playstore errors though. I think one of them is that it needs a feature graphic but I'm not really sure what else it could be complaining about

**Comment by jtmcn** [comment]
Feature graphic is the main thing missing. I've been putting it off because I wanted to update the icon, but never got around to it. I'll put together something simple for now.
