### ISSUE TITLE
Update Icons and Feature Graphic

### ISSUE THREAD

**Issue by kevinhinterlong** [jtmcn/archwiki-viewer#15]
There was an update to the icons from #6 but it got switched out while updating. Let me know if you want to update to this icon. 
Here's a preview
![New logo](https://github.com/jtmcn/archwiki-viewer/raw/3dd67bb81049fe8c4be892043de6de306054f23d/res/drawable-mdpi/archwiki_launcher.png)

**Comment by jtmcn** [comment]
Yes. This icon is better.

**Comment by kevinhinterlong** [comment]
Ok fixed in #17

**Comment by kevinhinterlong** [comment]
@jtmcn Do you have any ideas for a feature icon?
