### ISSUE TITLE
Upload to F-Droid

### ISSUE THREAD

**Issue by ZJaume** [jtmcn/archwiki-viewer#27]
This app is FOSS, why not available int F-Droid?

**Comment by kevinhinterlong** [comment]
We're currently working out some logistics with maintaining the project in the play store which should likely be finished soon. As soon as we finish that and are ready to push out an update we will do this.

**Comment by kevinhinterlong** [comment]
We've straightened out the play store issues. Here's the [F-Droid Submission](https://gitlab.com/fdroid/rfp/issues/183).

**Comment by kevinhinterlong** [comment]
I'm not sure when it will actually be added, but in the meantime just follow the [releases on GitHub](https://github.com/jtmcn/archwiki-viewer/releases) if you don't want/have access to the Play Store.

**Comment by ZJaume** [comment]
I have acces but, thank you!

**Comment by kevinhinterlong** [comment]
It's been added! 😄 I'll go ahead and close this.
