### ISSUE TITLE
v1.0.11 missing in F-Droid-Store

### ISSUE THREAD

**Issue by Krawei** [jtmcn/archwiki-viewer#43]
When I take a look in the playstore I notice, that the app's current version is v1.0.11.

In the F-Droid store the current version is v1.0. 7. There's no "unstable"-marked version in the F-Droid store so far.

What's the reason for the difference on the versions? Is there a failure in build process?

Kind Regards,

Krawei

**Comment by kevinhinterlong** [comment]
F-Droid updates based on the [release tags](https://github.com/jtmcn/archwiki-viewer/releases/tag/v1.0.11) from GitHub.
I made the github release after I put it in the playstore and as far as I can tell it can take a couple of days for the F-Droid repos to update, I'm sure it'll be there pretty soon.

You can always download it from the GitHub releases directly if you need it sooner.

**Comment by kevinhinterlong** [comment]
Just checked F-Droid and it looks like the new version is now available
