### ISSUE TITLE
Build fails, icon not found

### ISSUE THREAD

**Issue by gkaklas** [jtmcn/archwiki-viewer#5]
I'm trying to build the app with `ant debug` and I get this error:
```
res/layout/wiki_layout.xml:15: error: Error: No resource found that matches the given name (at 'src' with value '@drawable/ic_launcher')
```
Shouldn't there be an icon `ic_launcher.png` in each `drawable-*dpi` directory? If I copy and rename e.g. /ic_launcher-web.png the project builds successfully.
(I'm not sure, maybe I'm doing something wrong since I don't have much experience with Android, but I thought this was worth asking anyway)

**Comment by kevinhinterlong** [comment]
Yea it looks like there was a commit where the icons got removed so what you did was the correct fix for the problem. The icons have been added back in, but the project has been updated to Android Studio now.

**Comment by kevinhinterlong** [comment]
@jtmcn this can be closed
